winresult v0.1.1: fix docs.rs builds
error: couldn't read src/gen/codes/STATUS/../STATUS.rs: No such file or directory (os error 2)
it turns out windows will simplify the path despite STATUS/ (the directory) not existing
linux, however, will error out since the directory is missing